export type CheckTransactionStatusAPIResponse = {
  "trans-status"?: Partial<{
    "order-number": number;
    "transaction-amount": number;
    "transaction-date-and-time": number;
    status: string;
    "response-message": string;
    "response-code": number;
    "currency-code": number;
    "cc-type": string;
    "cardholder-name": string;
    "cardholder-surname": string;
    "cardholder-address": string;
    "cardholder-city": string;
    "cardholder-zip-code": string;
    "cardholder-email": string;
    "cardholder-phone": string;
    "cardholder-country": string;
    "installments-number": number;
    "card-details": string;
    "reference-number": number;
    "approval-code": number;
    acquirer_code: number;
    transaction_type: number;
    additional_order_number: string;
    [index: string]: string | number | Record<any, unknown>;
  }>;
};
export type ErrorAPIResponse = {
  errors?: {
    description: string;
    action: string;
    "order-states": string;
    order: Record<string, any>;
  };
};
export type GenericAPIResponse = ErrorAPIResponse & {
  order?: Partial<{
    "account-id": string;
    acquirer: string;
    "acquirer-code": number;
    "additional-order-number": string;
    "approval-code": number;
    "card-details": string;
    "card-profiles-id": string;
    "cardholder-address": string;
    "cardholder-city": string;
    "cardholder-country": string;
    "cardholder-country-code": string;
    "cardholder-email": string;
    "cardholder-name": string;
    "cardholder-phone": string;
    "cardholder-surname": string;
    "cardholder-zip-code": string;
    cart: string;
    "cc-type": string;
    comment: string;
    "company-id": number;
    "created-at": string;
    "cvv-active": boolean;
    direction: string;
    "expiration-date": number;
    "hashed-oib": string;
    "host-mid": string;
    id: number;
    "installments-number": number;
    ip: string;
    "is-for-ecc": boolean;
    language: string;
    "logged-in-user-sub": string;
    "mdc-time": string;
    "merchant-id": string;
    "message-id": number;
    mode: string;
    "new-hashed-oib": string;
    "order-number": number;
    "pay-by-link-id": string;
    "payment-number": string;
    "pbl-used": boolean;
    "pis-transaction-uuid": string;
    "promotion-discount-used": boolean;
    "reference-number": number;
    "require-complete": boolean;
    "response-code": number;
    "response-message": string;
    "service-type-indicator": number;
    source: string;
    status?: string;
    "store-id": number;
    subscription: boolean;
    "subscription-exp-date": string;
    systan: number;
    "terminal-id": string;
    "token-value": string;
    "transaction-amount": number;
    "transaction-currency": number;
    "transaction-date-and-time": number;
    "transaction-original-amount": number;
    "transaction-type": number;
    "updated-at": string;
    "use-card-profiles": boolean;
    "user-id": string;
    version: number;
    "visamdc-name": string;
    "voucher-amount": string;
    "wallet-type": number;
    "zaba-card": boolean;
  }>;
};
